### ISSUE TITLE
too many socket handlers

### ISSUE THREAD

**Issue by kokjason** [miekg/dns#1196]
I use it to do http dns. There are 600 http requests in a second. Then after several hours, I find there are about 103204 socket handlers by using cmd `lsof -p $PID | wc -l`.  

$ ps aux | grep -v grep | grep base
root      7237  3.1  2.0 5099000 2707408 ?     Sl   Nov23  27:57 ./bin/httpdns -c ./conf/base.toml
$ lsof -p 7237 | wc -l
103204

Can you help me fix it.

**Comment by kokjason** [comment]
I made a plan B which deal all requests in only one goroutine. It works OK. But the performance is very very slow. Can you help me to fix this issue? Just make it works OK in many goroutines. Thanks.

**Comment by tmthrgd** [comment]
This library doesn't implement any http/DNS-over-HTTPS support so I'm not sure we can help you at all. If you're using it as a DNS server with an http connection to some backend, you'll likely need to rate-limit or otherwise control the number of active HTTP requests. The fact that you seem to be leaking file descriptors/"socket handlers" sounds like you're not closing resources somewhere.
