### ISSUE TITLE
dns: buffer size too small

### ISSUE THREAD

**Issue by OJ** [miekg/dns#214]
Hi there,

Thanks for the great library. It's pretty handy and very easy to use.

As part of a small application I'm building, I'm making a number of queries to a custom DNS server using TXT records. As part of the response, I include some Base64-encoded 'stuff'. The first response I send is just a single unsigned short (16-bit) encoded as base64 and this works fine. Further down the track I do the same thing, but those subsequent results end up with the following error being returned from the `Exchange()` method (on the `dns.Client` instance):
```
dns: buffer size too small
```
And I'm not sure why. I pretty certain that I'm doing something stupid, but I was wondering if you could provide some insight as to why this error occurs and how I might be causing it to happen.

Thanks again.

**Comment by OJ** [comment]
Hi again,

I'm just following up with some more information. The cases where I am seeing it fail is where the domain names are really long, and it breaks [in msg.go right here](https://github.com/miekg/dns/blob/32c1cd51a98ca66b93ea5d54601891d26e4dd747/msg.go#L287). Hopefully that'll help. If I use `nslookup` (or similar) on the same domain, I don't receive any errors.

Thanks again!

**Comment by OJ** [comment]
If I submit DNS TXT lookup for a domain that is a total of 247 characters, including 7 labels, then I get the error shown above. If I reduce this down to 245 characters, the error changes to:
```
dns: overflow unpacking uint32
```
Note that if I configure my server to respond to the original TXT query with a blank message, I receive no error.

Cheers!

**Comment by andrewtj** [comment]
Some of the symptoms you've mentioned could be due to hitting the limit of [dns.Client](http://godoc.org/github.com/miekg/dns#Client)'s `UDPSize`.

**Comment by OJ** [comment]
Thanks @andrewtj. Is this something that's a hard limit specified by the DNS protocol, or is that something that is a limitation of this library? Pardon my ignorance. The reason I ask is because the likes of `nslookup` doesn't have any issues with the exact same requests. Thanks again!

**Comment by OJ** [comment]
As a final note, I just thought I'd say that when I use the built-in functionality of `net.LookupTXT()` I do not receive any errors at all. I just thought I'd add this as a point of comparison.

Thank you again, sorry for the comment spam.

**Comment by andrewtj** [comment]
In a nutshell: 512 bytes is the by-the-RFC UDP size limit for a message and servers should set the TC bit and truncate responses that exceed that limit. Transmission over TCP raises that limit to 64k. EDNS0 can also lift the maximum UDP payload to 64k though you're unlikely to get near that over the internet.

I'd guess `nslookup` is EDNS enabled (not really familiar with it) and so is prepared to receive a larger datagram from your custom server. If your custom server doesn't implement truncation and EDNS and it's going to serve the internet at large, you'll want to implement both those features. If you're only serving your own clients you can probably get away with just bumping buffer sizes.

**Comment by OJ** [comment]
@andrewtj that's a really interesting insight, thanks for the sharing the knowledge. I won't only be serving my own clients, but for this functionality the only clients that will make use it of it will be my own, so I might be able to get away with it that way. Cheers.

**Comment by andrewtj** [comment]
@OJ just be a bit wary of how useful those larger responses might be to an attacker ;)

Oh and there could still be a bug or two here. Let us know how you get on.

**Comment by OJ** [comment]
@andrewtj I clearly need to ramp up my knowledge here as I'm flying around like a noob! My responses are, at this point, a small 5-byte blob. The rest is what is expected by default. I'll dig deeper and see what I can come up with. I'll be sure to let you know if I find anything sinister.

Attacker? I can neither confirm nor deny that it's me ;)

Cheers again for your time and help dude.

**Comment by miekg** [comment]
Closing.

**Comment by prisamuel** [comment]
I'm seeing this same issue when using this library for querying SRV records from Consul's DNS interface. 

When the message size is smaller than 512, my requests succeed. But when the response size increases to 538 B I get an error with "dns: buffer size too small".

A typical Consul SRV response looks like this:
`bash-4.3# dig example.service.consul SRV

; <<>> DiG 9.10.2 <<>> example.service.consul SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42745
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 2

;; QUESTION SECTION:
;example.service.consul. IN	SRV

;; ANSWER SECTION:
example.service.consul. 0 IN	SRV	1 1 32866 core-i-0a2b2rewr58f-172.17.5.34.node.dc1.consul.
example.service.consul. 0 IN	SRV	1 1 32866 core-i-7fafffwerwwff-172.17.4.151.node.dc1.consul.

;; ADDITIONAL SECTION:
core-i-0a2b2rewr58f-172.17.5.34.node.dc1.consul. 0 IN A	172.17.5.34
core-i-7fafffwerwwff-172.17.4.151.node.dc1.consul. 0 IN A 172.17.4.151

;; Query time: 3 msec
;; SERVER: 10.0.42.1#53(10.0.42.1)
;; WHEN: Fri Feb 19 12:58:10 UTC 2016
;; MSG SIZE  rcvd: 373`

On the RFC I see:
A field that specifies the length in bytes of the UDP header and UDP data. The minimum length is 8 bytes because that is the length of the header. The field size sets a theoretical limit of 65,535 bytes (8 byte header + 65,527 bytes of data) for a UDP datagram. The practical limit for the data length which is imposed by the underlying IPv4 protocol is 65,507 bytes (65,535 − 8 byte UDP header − 20 byte IP header)

This is well below the specified limit.

**Comment by andrewtj** [comment]
@prisamuel The RFC quoted without reference reads as though it is talking about UDP in general. [RFC 1035](http://tools.ietf.org/html/rfc1035) section 2.3.4 set the 512 byte limit. It can be increased with the extension mechanism outlined in [RFC 6891](https://tools.ietf.org/html/rfc6891). If there's room for improvement in this package or you have questions on its use a new issue is probably appropriate.

**Comment by asergeyev** [comment]
I guess it's now default to dig to send and expect 4096 bytes.  Should dns lib client by default have same behavior?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] dns: buffer size too smal..." ]
>I guess it's now default to dig to send and expect 4096 bytes.  Should dns lib client by default have same behavior?

Add edns0 bufsize to a message if there is none?

**Comment by asergeyev** [comment]
or have client option...  not sure.

**Comment by prisamuel** [comment]
@andrewtj 
Sure, I'll go ahead and create a new issue for discussing this. Sorry for the unreferenced RFC. I was quoting [RFC 2675](https://tools.ietf.org/html/rfc2675l). It is talking about jumbogram extensions for UDP in general.

It looks like adding edns0 support to the message buffersize might solve the issue. It's up for discussion.
