### ISSUE TITLE
Create a msg.Deduplicate function/method

### ISSUE THREAD

**Issue by miekg** [miekg/dns#225]
Copy/improve SkyDNS' dedup <https://github.com/skynetservices/skydns/blob/0078e9f5139e334e75b6f16f1faa4c938ed79954/server/server.go#L875> function over in this lib.

**Comment by miekg** [comment]
Another being tested/implemented in SkyDNS: short CNAMEs before A/AAAA in a message. This is not to break stub-resolvers like glibc.

**Comment by miekg** [comment]
Dedup should work on a `[]dns.RR`. Should it also sort CNAMEs before A records? If so `Cleanup` might be a better name (or at least something different than Dedup). It also ties in with #223 because dedupping makes the msg smaller.

In general I think we want:
* `Dedup([]RR)`
* `SomethingSomething(dns.Msg)` that does dedup as one of the steps.

**Comment by miekg** [comment]
Adding some commments from @asergeyev in here

* ideally work on wireformat and get the TTL out from there, dropping the whole Sprintf (for now at least)
* check the TTLs and keep the longest value when dedupping
* Look at CNAMEs as well, maybe DNAME and friends and filter those too
* Normalize the domain name before comparing, because of DNS case preservation crap
* A Go `map` might not be the best thing for this.

**Comment by michaelharo** [comment]
It looks like this post has been changed since it arrived in email.  Re TTL longest vs shortest values...

http://tools.ietf.org/html/rfc2181#section-5.2

Should an authoritative source send such a malformed RRSet, the
   client should treat the RRs for all purposes as if all TTLs in the
   RRSet had been set to the value of the lowest TTL in the RRSet.  In
   no case may a server send an RRSet with TTLs not all equal.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Create a msg.Deduplicate ..." ]
>It looks like this post has been changed since it arrived in email.  Re TTL longest vs shortest values...

Yes, I edited after I saved. Github sends immediately.

>http://tools.ietf.org/html/rfc2181#section-5.2
>
>Should an authoritative source send such a malformed RRSet, the
>   client should treat the RRs for all purposes as if all TTLs in the
>   RRSet had been set to the value of the lowest TTL in the RRSet.  In
>   no case may a server send an RRSet with TTLs not all equal.

Yep, indeed we want lowest.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
As for normalizing, in `dnssec.go` we have: https://github.com/miekg/dns/blob/master/dnssec.go#L289 (`strings.ToLower`). There is a `bytes.ToLower` that might work as intended on the packed byte slice.

**Comment by asergeyev** [comment]
strings.ToLower and bytes.ToLower are identical ... Create new string/byteslice by passing runes thru map func. Since that func is probably not allowed to mess with "source material";  you might want to check if there are chars in A-Z range before you call it (lowercasing of non-ASCII characters in dns labels is not allowed by RFC I think...)

**Comment by asergeyev** [comment]
(and if there are places where you can mess with source racing thru bytes and inplace adding 0x20 to A-Z is usually faster)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Create a msg.Deduplicate ..." ]
>(and if there are places where you can mess with source racing thru bytes and inplace adding 0x20 to A-Z is usually faster)

Ack, we can do that later. Right now I *can* mess with the material because I
have a freshly allocated buffer.

**Comment by miekg** [comment]
Multiple iterations done. Settled on the one I just merged, API might still change though.
