### ISSUE TITLE
fix failing test: TestSingleInflight

### ISSUE THREAD

**Issue by miekg** [miekg/dns#250]
```
github.com/miekg/dns
github.com/miekg/dns/idn
20.15s$ go test -race -bench=.
--- FAIL: TestSingleSingleInflight-2 (0.01s)
	client_test.go:200: all rtts should be equal.  got 678575 want 756598
	client_test.go:200: all rtts should be equal.  got 699434 want 756598
	client_test.go:200: all rtts should be equal.  got 699434 want 756598
	client_test.go:200: all rtts should be equal.  got 1252951 want 756598
	client_test.go:200: all rtts should be equal.  got 1252951 want 756598
	client_test.go:200: all rtts should be equal.  got 1252951 want 756598
	client_test.go:200: all rtts should be equal.  got 1252951 want 756598
	client_test.go:200: all rtts should be equal.  got 580212 want 756598
	client_test.go:200: all rtts should be equal.  got 580212 want 756598
```

**Comment by miekg** [comment]
Can't reproduce locally (with 1.4 nor 1.5)

**Comment by asergeyev** [comment]
TestSingleSingleInflight not TestSingleSingleInflight, right?

You're testing INT64 time values there, they all carry variability from goroutine scheduling in golang core, you have decent chances to hit outlier in first element and therefore have error all the way thru the test.

IMO testing RTT being certain number is not helpful at all... VMs are noisy and even on solid 100% dedicated for this test server you can see NTPD shifting time during the test and it'll fail anyway. 

If you strongly desire to keep this test it's possible to see that test is generating set of 100+ values where:
* none are 0
* on histogram, majority of values hit same bucket as the median

IMO it's still all overkill...   Premise of the test is that there is no extra time spent on things except the latency between server and client but, since your server is process-inlined and latency is measured in nano and micro-seconds it's unlikely to have that information derived from RTT. You'd always pick go runtime and system noise.

**Comment by miekg** [comment]
Agreed.

**Comment by asergeyev** [comment]
Remove this test or change what it's checking?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] fix failing test: TestSin..." ]
>Remove this test or change what it's checking?

Remove (didn't get around to doing that)

**Comment by asergeyev** [comment]
in case if you want to test c.SingleInflight feature we could design/discuss possible replacement.

So far the feature actually has:

    // This adds a bunch of garbage, TODO(miek).

attached to code.. maybe something to look into?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] fix failing test: TestSin..." ]
>in case if you want to test c.SingleInflight feature we could design/discuss possible replacement.
>
>So far the feature actually has:
>
>    // This adds a bunch of garbage, TODO(miek).
>
>attached to code.. maybe something to look into?

the lookup key is created every single time, from memory it concats a bunch of
things. That could add up. But I haven't figured out a smarter way of doing that
(yet).

/Miek

--
Miek Gieben

**Comment by asergeyev** [comment]
Just to make sure... Idea is to give answer to group of "same queries" without sending them multiple times, right?

**Comment by miekg** [comment]
Yep

**Comment by asergeyev** [comment]
I was poking at things and come up with small test that only checks single-in-flight behavior.. I wonder if you want me to polish it to include or no. 

There is also possibility to change flow of things slightly to use of sync.Pool in order to lazily reuse once created "call" structs... Will limit amount of heap garbage... As for string keys... I'm not sure yet... It's possible to create something better but I have doubts that it worth it.

Another note... It's possible to make call survive a little longer and be re-used an RTT-long after original request completes but IMO it's out of scope a bit... and more like "CacheAnswers" than "SingleInFlight".
