### ISSUE TITLE
dns msg length not matched the origin dns resolver

### ISSUE THREAD

**Issue by netroby** [miekg/dns#295]
```
s ~ # drill www.google.com @208.67.220.220 -p 443
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 26501
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; www.google.com.	IN	A

;; ANSWER SECTION:
www.google.com.	300	IN	A	216.58.221.100

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 115 msec
;; SERVER: 208.67.220.220
;; WHEN: Mon Dec 21 12:43:39 2015
;; MSG SIZE  rcvd: 48

```
and 
```
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 2140
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; www.google.com.	IN	A

;; ANSWER SECTION:
www.google.com.	300	IN	A	216.58.221.100

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Mon Dec 21 12:43:52 2015
;; MSG SIZE  rcvd: 62

```

The first was origin dns resolver msg length,
the second is the dns client resolved name by miekg/dns client

**Comment by andrewtj** [comment]
I think that's due to name compression. 62 - 48 = 14. `www.google.com.` uncompressed is (1+3)+(1+6)+(1+3)+(1+0) = 16. The second time that name appears it can be compressed and a compression pointer only takes 2 bytes.

Setting `Compress` on `Msg` determines whether compression will be attempted. In general don't expect a message produced by another implementation to repack to the same size, though in this case it probably will.

**Comment by netroby** [comment]
Ok, thants, that solved my problem. thanks
