### ISSUE TITLE
track rtt and dynamically scale the timeout

### ISSUE THREAD

**Issue by miekg** [miekg/dns#336]
The time in dns.Client is hard codes (or chosen by the user), but fixed. It would be nice to keep a table with rtt and dynamically set the timeout based on the IP address of the upstream server. This should lead to shorter timeouts, while not giving up on reliability.

**Comment by rolandshoemaker** [comment]
It might be nicer to add another method to `Client`, `ExchangeWith{Deadline,Timeout,Context}` or something, so that implementers can easily define their own timeout scaling methods as motivations will probably vary considerably depending on what the usage is.

**Comment by miekg** [comment]
That sounds like a sensible plan. And then provide a implementation in the lib.

**Comment by jsha** [comment]
+1 to `ExchangeContext`, which could use `net.DialContext`, and set deadlines based on the deadline in the context (if present).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] track rtt and dynam..." ]
>+1 to `ExchangeContext`, which could use `net.DialContext`, and set deadlines based on the deadline in the context (if present).

Ack. Send code! ExchangeContext sgtm.
Would a DialContext also fix #471?
(I have zero time to work on this on the forseeable future - too busy with 
coredns).

d

**Comment by jsha** [comment]
Thanks for acking! Will try to write up a PR. DialContext would not fix #471. Contexts are mainly about timeouts and "extra data" (especially tracking data through RPCs etc), but don't care about `LocalAddr`. In #471, a `net.Dialer` is constructed in order to set `LocalAddr`. The `net.Dialer` type also has both `Dial` and `DialContext`, just like the top-level package functions. So there would be some work the deconflict the two PRs based on what lands first.

**Comment by miekg** [comment]
Ack. I think this is Ok. The `localAddr` can also be done by getting a `Conn` and making it into a `dns.Conn`.

**Comment by miekg** [comment]
We have a dns.Dialer now, allows someone to do this. Closing here.
