### ISSUE TITLE
Question: How do I send an update to a DNS server to update a CNAME and Arecord ?

### ISSUE THREAD

**Issue by hydroflame** [miekg/dns#401]
```
m := new(dns.Msg)
r, _ := dns.NewRR("foo.company.net. 3600 A 127.0.0.1")
m.WHATDOIDONOW(r)
```

I'm at a lost, I tried most of the functions on dns.Msg and can't find anything that doesn't end up in an error. Real newbie here (re dns not Go) so if you just want to point me to a document that explain DNS that would be fine,

**Comment by andrewtj** [comment]
[RFC 2136](https://tools.ietf.org/html/rfc2136) and then the [Dynamic Updates](https://godoc.org/github.com/miekg/dns#hdr-DYNAMIC_UPDATES) section of the docs would be a good place to start. Let us know how you get on.

**Comment by hydroflame** [comment]
Ok I've read a bit and understand a tiny bit more

```
m := new(dns.Msg)
m.SetQuestion("platform.company.net", 3600)
r, err := dns.NewRR("foo.platform.company.net. 3600 A 127.0.0.1")
m.Ns = []dns.RR{r}
resp, _, err := c.Exchange(m, "int-ddns01.resource.company.net:53")
w.Write([]byte(resp.String()))
```
(error handling omited for brievety)

I'm getting a `domain must be fully qualified`. My problem might be in the Question (which is zone when doing dynamic updates) but I can't tell what's wrong

**Comment by hydroflame** [comment]
ok first problem resolved, I need to add a period after the fqdns

**Comment by hydroflame** [comment]
Ugh, apparently it'll take a while for my $WORK DNS to update, can someone confirm that the code looks correct ?

**Comment by andrewtj** [comment]
The `status: FORMERR` in the response means the server rejected the query. In this case that's probably due to:

> `m.SetQuestion("platform.company.net", 3600)`

The second parameter to `SetQuestion` is a Type and must be `dns.TypeSOA` for an Update query.

> `m.Insert([]dns.RR{r})`

Keep in mind that this is additive and does not replace existing records.

Regarding update times, it's unusual for the server that accepts Updates to not immediately reflect changes. That's not to say that all the authoritative servers will immediately reflect the change, just that the one that accepts the Update will generally reflect the change immediately.

**Comment by hydroflame** [comment]
changing for TypeSOA gives me a slightly different result but still Format Error (and not Forme RR as I originally thought)
```
;; opcode: QUERY, status: FORMERR, id: 2825
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;platform.company.net.	IN	 SOA
```

**Comment by hydroflame** [comment]
I tried with nsupdate(8) and that worked just fine

**Comment by hydroflame** [comment]
Ok eventualyl figured out everything, ty
