### ISSUE TITLE
Unexpected empty string returned from `ToPunycode` 

### ISSUE THREAD

**Issue by RBeaudoin** [miekg/dns#490]
When I execute the following:

``` Go
func main() {
 fmt.Println(idn.ToPunycode("❤.rust-lang.org"))
}
```

It prints the empty string. I would expect the `ToPunycode` method to return `xn--qei.rust-lang.org`

**Comment by rafaeljusto** [comment]
The domain `❤.rust-lang.org` did not convert also in the [Verisign IDN Tool](https://www.verisign.com/en_US/channel-resources/domain-registry-products/idn/idn-conversion-tool/index.xhtml). I got it converted in [Punycoder](https://www.punycoder.com/) website. The code point 10084 (❤) is disallowed in this library due to `CURVED STEM PARAGRAPH SIGN ORNAMENT..HEAVY W` ([reference](https://github.com/miekg/dns/blob/master/idn/code_points.go#L1556)) and follows [RFC 5892 - Appendix A](https://tools.ietf.org/html/rfc5892#appendix-A).

**Comment by RBeaudoin** [comment]
Thanks @rafaeljusto 

This seems to be a code point that is allowed in some implementations, but not others. The RFC does seem to clearly indicate that it is not allowed.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Unexpected empty st..." ]
>Thanks @rafaeljusto
>
>This seems to be a code point that is allowed in some implementations, but not others. The RFC does seem to clearly indicate that it is not allowed.

File an errata! Which would help and might lead to a follow up RFC

**Comment by andrewtj** [comment]
@RBeaudoin are you satisfied with @rafaeljusto's explanation or would you like to start a conversation about (potentially) adding additional API?

**Comment by RBeaudoin** [comment]
@andrewtj yes, thank you. At Heroku we had to switch to another library because Let's Encrypt supports  issuing certs for emoji domains, and we do pre-validation.

I completely understand it's not in the spec though, and appreciate the explanation.

**Comment by miekg** [comment]
https://github.com/miekg/dns/pull/584 (removes our implementation of idn)
