### ISSUE TITLE
Use workers instead spawning goroutines for each incoming DNS request

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [miekg/dns#639]
There are two major issues:
unlimited using resources - performance test shows that on high load CoreDNS silently crashed due out of memory;
performance drop due much time is spent on management goroutines instead serve DNS requests.

**Comment by miekg** [comment]
How does net.http handle this? Also unbounded?

**Comment by tmthrgd** [comment]
@miekg For HTTP/1.x `net/http` uses a single goroutine per-connection without any sort of limit or pool. HTTP/2 on the other hand uses a per-request goroutine (multiple requests can occur per-connection). Interestingly the HTTP/2 code actually has [a knob](https://github.com/golang/net/blob/f5dfe339be1d06f81b22525fe34671ee7d2c8904/http2/server.go#L84-L88) to limit the number of goroutines, but it was just never implemented.

The comparison to `net/http` may not be the most relevant as they deal with multiple requests over TCP connections, not the standard UDP packet per-request of DNS. This does seem like it could be quite valuable nonetheless. There is reference in #565 about there being more background (performance numbers and such) is there any chance we could see them and understand how compelling a change could be?

(A quick skim over #565 highlights a problem with handling TCP queries so if this goes ahead it will need a little more refactoring).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Use workers instead..." ]
>(A quick skim over #565 highlights a problem with handling TCP queries so if this goes ahead it will need a little more refactoring).

Thanks, this provides some valuable background. I'm leaning towards acking a PR 
like this. The major factor why I dislike it, is because it implements policy 
(the const that says 100 workers should be run) and this will bite us at some 
points. Exporting config options to users is also a new thing for this library.

Another way of fixing this (for CoreDNS) would be implementing a ratelimit 
plugin.

**Comment by UladzimirTrehubenka** [comment]
https://github.com/miekg/dns/pull/664

**Comment by UladzimirTrehubenka** [comment]
I have implemented dynamic worker spawn - so we don't need 'magic' number of workers.

**Comment by UladzimirTrehubenka** [comment]
https://github.com/miekg/dns/pull/664 was merged.
