### ISSUE TITLE
Undefined ed25519 parameters

### ISSUE THREAD

**Issue by mingard** [miekg/dns#744]
Testing with Go v1.10 and 1.11 I get the following errors. 

```
dnssec_keyscan.go:183:18: undefined: ed25519.SeedSize
dnssec_keyscan.go:186:8: undefined: ed25519.NewKeyFromSeed
dnssec_privkey.go:85:24: p.Seed undefined (type ed25519.PrivateKey has no field or method```

**Comment by tmthrgd** [comment]
How are you building it? The vendor directory contains the updated code so this failure doesn’t make much sense.

**Comment by jstorer** [comment]
getting the same errors building inside goland or running 'go test' from command line

**Comment by tmthrgd** [comment]
I don’t have enough information, but I’m pretty sure you must be building outside of `$GOPATH` and hitting golang/go#14566. I don’t think the vendor directory is ignored otherwise.

You likely have an outdated copy of golang.org/x/crypto/ed25519 in your `$GOPATH`, try running `go get -u golang.org/x/crypto/ed25519`.

I’m going to close this, but feel free to reopen if that doesn’t solve your problem.
