### ISSUE TITLE
'not supported by windows' in setUDPSocketOptions

### ISSUE THREAD

**Issue by larytet** [miekg/dns#796]
Both calls to SetControlMessage() in the func setUDPSocketOptions(conn *net.UDPConn) return error 'not supported by windows'

Windows 8.1 Enterprise 64-bit

**Comment by larytet** [comment]
Apparently it is fixed by https://go-review.googlesource.com/c/net/+/76394

**Comment by tmthrgd** [comment]
You need to update this package.

It was broken by https://github.com/miekg/dns/commit/bfbb1715afbeb1e50ce72970d31f71564ae94c6f on September 9, and fixed by https://github.com/miekg/dns/commit/edac0c6ab3143c198c2d5fd7faa8c4aafecc5420 on September 29.

When the upstream issues are fixed then the first PR can be reattempted.
