### ISSUE TITLE
DSA SHA1 Algorithm

### ISSUE THREAD

**Issue by semihalev** [miekg/dns#801]
Are there any implementation about this in the future? I got some bad algorithm errors while verifying from some domains (for example: onetsolutions.me)

**Comment by miekg** [comment]
Think DSA has been deprecated for dnssec a long time ago. I would treat
this algo as insecure.

**Comment by tmthrgd** [comment]
There has been talking about removing DSA support from x/crypto/openpgp (see golang/go#27905), so I don't think DSA support should be added without good reason because it is notably insecure. `DSA/SHA-1` is also marked as optional by [RFC 6944](https://tools.ietf.org/html/rfc6944).

@semihalev How many domains with `DSA/SHA-1` have you come across? I agree with @miekg that treating them as insecure is very likely the most correct approach, and perhaps contacting the domain owners.
