### ISSUE TITLE
moving some standalones packages from CoreDNS to miekg/dns

### ISSUE THREAD

**Issue by chantra** [miekg/dns#962]
https://github.com/coredns/coredns/plugin/test (except for scrape) and https://github.com/coredns/coredns/plugin/pkg/dnstest 

while part of CoreDNS, they have no dependencies on anything else specific to CoreDNS and are great packages to get unittesting bootstrapped in little time when builtin on top of miekg/dns

Another package which has no dependency within CoreDNS and that is also very helpful is 

https://github.com/coredns/coredns/request .

Those packages have great value for anybody using miekg/dns and I would love to see those available within miekg/dns, or maybe some other repository which people could import with limited dependencies.

What do you folks think?

As mentioned to @miekg offline, I did end up copying those from CoreDNS manually, because of their usefulness and low dependencies, but having an upstream repo to pull from would be better, both in term of keeping imports up to date, but also in broadening the number of project that can use those packages, find/fix bugs and contribute back.

**Comment by miekg** [comment]
Nice to hear you think those pkgs are useful.

There is always the tradeoff between amount of code, visibility and if things belong in a fairly low level library is this one.

For one; they can be spun off in separate pkgs inside the coredns repo; but this can be annoying if you want to do an atomic change (also some of our automation and OWNERS needs to be redone).

Having a dns/dnstest has been discussed before and I'm not against this, also because this mirror http/httptest on which large parts of this pkg have been modelled.

**Comment by chantra** [comment]
> There is always the tradeoff between amount of code, visibility and if things belong in a fairly low level library is this one.

yeah, which is why I mentioned possibly some other repository.

> Having a dns/dnstest has been discussed before and I'm not against this, also because this mirror http/httptest on which large parts of this pkg have been modelled.

that would be a great start :) and I would be happy to help moving some of this stuff around.

**Comment by miekg** [comment]
wont happen any time soon. I also like this to be a small contained repo/pkg
