### ISSUE TITLE
Truncate should set TC flag more often

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#987]
On #854, @markdingo raised the following:

> On a related front, I think the logic behind setting the Truncate flag is a bit simplistic.
> 
> The code comment says "According to RFC 2181, the TC bit should only be set if not all of the answer RRs can be included in the response." and the code does precisely this. But that's not what RFC2181 says. It says TC should be set if a "required" RRSet doesn't fit, regardless of whether that required RRSet is in the answer section or not.
> 
> Admittedly that whole section in RFC2181 is pretty muddled, but there is at least one use-case where TC should be set when the additional section is truncated. That's when the additional section contains referral/glue RRs for a sub-domain. By way of example, if we imagine a query to an example.net name server for sub.example.net/NS which results in:
> 
> ;; QUESTION SECTION:
> ;sub.example.net.               IN      NS
> 
> ;; AUTHORITY SECTION:
> sub.example.net.        172800  IN      NS      c.sub.example.net.
> sub.example.net.        172800  IN      NS      a.sub.example.net.
> sub.example.net.        172800  IN      NS      b.sub.example.net.
> 
> ;; ADDITIONAL SECTION:
> c.sub.example.net.       172800  IN      A       ...
> a.sub.example.net.       172800  IN      A       ...
> b.sub.example.net.       172800  IN      A       ...
> 
> If just the additional section is truncated by msg.Truncate() then the client will fail to resolve the sub-domain as it won't see TC=1 to re-query with TCP and trying to resolve the sub NS address via the parent doesn't work since the address RRs are glue. You can try this for yourself with one of the TLDs such as .com. Imagine the additional section for google.com/NS is truncated with TC=0. You'll never be able to resolve google.com as you never see the NS address glue and can't get at it directly via the .com servers.
> 
> The problem here is that msg.Truncate() really has no idea whether non-Answer RRSets are "required" or not since it's just a generic function that is oblivious to the caller's intentions or role.
> 
> I'm not sure what the right approach is. Either the description of msg.Truncate() should accurately reflect that it's setting of TC is only a guide and the caller really has to make the final TC=1 decision. Alternatively it could follow the approach that PowerDNS takes in the next release which is to set TC on *any* truncation. This doesn't disagree with RFC2181 and it is a safer approach.
> 
> And, if you think about it, setting TC=1 only with an Answer truncation vs any truncation is mostly just a corner-case optimisation so forgoing this optimisation is unlikely to be harmful so the powerDNS approach isn't terrible.
> 
> Maybe not knowing what is "required" as per RFC2181 explains why some of the main DNS packages force the matter by wiping out *all* sections and setting TC=1 when any truncation is needed? They never give the client a chance to use a partial answer.
> 
> Anyway, there is at least one use-case where relying on msg.Truncate() to set TC correctly seems to be risky.

I’m opening a new issue since that PR has already been merged and comments aren’t always seen.

I’m fine making this change if others agree. The reasoning is sound and setting the TC flag when any record was removed was how I originally planned to implement this.

**Comment by markdingo** [comment]
> I’m opening a new issue since that PR has already been merged and comments aren’t always seen.

Thanks Tom.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Truncate should set TC ..." ]
>> I'm not sure what the right approach is. Either the description of msg.Truncate() should accurately reflect that it's setting of TC is only a guide and the caller really has to make the final TC=1 decision. Alternatively it could follow the approach that PowerDNS takes in the next release which is to set TC on *any* truncation. This doesn't disagree with RFC2181 and it is a safer approach.

I like the PowerDNS approach the most as this doesn't require to somehow interpret 
the response (i.e. is it a referral?).

**Comment by markdingo** [comment]
> I like the PowerDNS approach the most as this doesn't require to somehow interpret the response (i.e. is it a referral?).

Yeah, I wondered about "interpreting" too. Trying to understand whether additional has referral info or something else that is "required" seems like a complexity minefield. It also presupposes that we know about future dependencies that could end up in non-Answer sections such as cryptographic keys or DNSSEC related material or who knows what?

Unfortunately TC is binary but it's trying to serve two masters so taking the PowerDNS approach eliminates the benefits that the current implementation is trying to offer to the first master.

The two masters of course are a) Have Answers been truncated and b) has the DNS packet been truncated.

By far the "Have Answers been truncated" is of interest to the overwhelmingly dominant A/AAAA queries which is what the current msg.Truncate() implementation cares about but we're now saying that the risk to the other master is non-zero so the majority have to suffer.

What we really need are two TC bits. One to say Answers has been truncated and one to say the packet has been truncated but TCP re-queries are cheap these days and larger EDNS0 query support is pervasive so why bother with the complexity?

So yeah, I think PowerDNS is doing the right thing. I also think that even tho most DNS implementations clear all Answers when they set TC=1 (because they expect a re-query) the smart move is what msg.Truncate() does which is to leave as much intact as possible in case a client is incapable of re-querying.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Truncate should set..." ]
>So yeah, I think PowerDNS is doing the right thing. I also think that even tho most DNS implementations clear all Answers when they set TC=1 (because they expect a re-query) the smart move is what msg.Truncate() does which is to leave as much intact as possible in case a client is incapable of re-querying.

"incapable of re-querying" is basically anything that use musl libc - unless 
they have implemented DNS over TCP now.

/Miek

--
Miek Gieben

**Comment by markdingo** [comment]
> "incapable of re-querying" is basically anything that use musl libc - unless they have implemented DNS over TCP now.

Or if you're forwarding a packet to a limited resolver/proxy. I don't know whether it's still the case, but at some point dnsmasq only supported UDP queries and it's embedded in a lot of home routers and DSL gateways and the like.

In fact dnsmasq used to clear TC=1 on inbound packets because it knew it couldn't answer TCP queries. I think that's wrong, but quite possibly it was to protect against clients which presumed that they could discard their partial UDP response and get a bigger response via TCP before they actually made the re-query.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Truncate should set..." ]
>> "incapable of re-querying" is basically anything that use musl libc - unless they have implemented DNS over TCP now.
>
>Or if you're forwarding a packet to a limited resolver/proxy. I don't know whether it's still the case, but at some point dnsmasq only supported UDP queries and it's embedded in a lot of home routers and DSL gateways and the like.
>
>In fact dnsmasq used to clear TC=1 on inbound packets because it knew it couldn't answer TCP queries. I think that's wrong, but quite possibly it was to protect against clients which presumed that they could discard their partial UDP response and get a bigger response via TCP before they actually made the re-query.

Wow...

anyway: a PR implementing this will be merged :)

**Comment by markdingo** [comment]
I like the change but I wonder whether it's missing the fact that the EDNS0 RR is removed at the top of the code and re-appended at the end *after* the length check? Note the popEdns0() call at the top of the function?

Maybe a test case with a call to SetUDPSize(4096) would catch this?

As an aside, with that change to the semantics, can the truncation of the RR slices be avoided if Truncated is not set? Probably a silly optimisation, but why not?

if dns.Truncated {
        dns.Answer = dns.Answer[:numAnswer]
        dns.Ns = dns.Ns[:numNS]
        dns.Extra = dns.Extra[:numExtra]
}
