### ISSUE TITLE
data race found in ExchangeContext()

### ISSUE THREAD

**Issue by sda0** [miekg/dns#988]
Pls take a look at the problem below
```
WARNING: DATA RACE
Write at 0x00c0003d6100 by goroutine 35:
  myproject/vendor/github.com/miekg/dns.(*Client).ExchangeContext()
      /go/src/myproject/vendor/github.com/miekg/dns/client.go:501 +0x11b
  myproject/gateway.(*DNSClient).dig()
      /go/src/myproject/gateway/dns_client.go:113 +0x2b8

Previous write at 0x00c0003d6100 by goroutine 33:
  myproject/vendor/github.com/miekg/dns.(*Client).ExchangeContext()
      /go/src/myproject/vendor/github.com/miekg/dns/client.go:501 +0x11b
  myproject/gateway.(*DNSClient).dig()
      /go/src/myproject/gateway/dns_client.go:113 +0x2b8

==================

WARNING: DATA RACE
Read at 0x00c0000726c0 by goroutine 33:
  myproject/vendor/github.com/miekg/dns.(*Client).exchange()
      /go/src/myproject/vendor/github.com/miekg/dns/client.go:401 +0x6d6
  myproject/vendor/github.com/miekg/dns.(*Client).Exchange()
      /go/src/myproject/vendor/github.com/miekg/dns/client.go:137 +0x44f
  myproject/vendor/github.com/miekg/dns.(*Client).ExchangeContext()
      /go/src/myproject/vendor/github.com/miekg/dns/client.go:502 +0x16c
  myproject/gateway.(*DNSClient).dig()
      /go/src/myproject/gateway/dns_client.go:113 +0x2b8

Previous write at 0x00c0000726c0 by goroutine 32:
  myproject/vendor/github.com/miekg/dns.(*Client).ExchangeContext()
      /go/src/myproject/vendor/github.com/miekg/dns/client.go:501 +0xac
  myproject/gateway.(*DNSClient).dig()
      /go/src/myproject/gateway/dns_client.go:113 +0x2b8

```

**Comment by jsha** [comment]
Some ideas on implementation:

Instead of `ExchangeContext` calling `Exchange` (and then `exchange`), copy the implementation of `Exchange` and `exchange` into `ExchangeContext` and `exchangeContext`, then swap out `c.Dial()` with a new function `c.DialContext`. Additionally, the new `exchangeContext` would be modified to apply the overall context deadline to reads and writes, which it looks like the current `ExchangeContext` doesn't do.

`c.DialContext` would actually be a rename of `c.Dial`. We'd replace the `d.Dial` call with `d.DialContext`. Unfortunately, there's also a code path that calls `tls.DialWithDialer`, which appears to have no context variant yet. This could be partially worked around by using `d.Dial` to get a conn, and then building a `tls.Client` on top of it. Unfortunately, in this situation, the `tlsClient.Handshake()` method still disobeys the context deadline.

c.Dial` could then be implemented by calling `c.DialContext` with `context.Background()`.

Maybe another approach would be to add a `net.Dialer` parameter to the call signature for `.exchange()`, and make full copies of `c.Dialer` on each `ExchangeContext` call?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] data race found in ..." ]
>Some ideas on implementation:
>
>Instead of `ExchangeContext` calling `Exchange` (and then `exchange`), copy the implementation of `Exchange` and `exchange` into `ExchangeContext` and `exchangeContext`, then swap out `c.Dial()` with a new function `c.DialContext`. Additionally, the new `exchangeContext` would be modified to apply the overall context deadline to reads and writes, which it looks like the current `ExchangeContext` doesn't do.
>
>`c.DialContext` would actually be a rename of `c.Dial`. We'd replace the `d.Dial` call with `d.DialContext`. Unfortunately, there's also a code path that calls `tls.DialWithDialer`, which appears to have no context variant yet. This could be partially worked around by using `d.Dial` to get a conn, and then building a `tls.Client` on top of it. Unfortunately, in this situation, the `tlsClient.Handshake()` method still disobeys the context deadline.
>
>c.Dial` could then be implemented by calling `c.DialContext` with `context.Background()`.

This sounds like a fair approach to try it. Should will file an upstream bug for 
tls not having a context?

/Miek

--
Miek Gieben

**Comment by tmthrgd** [comment]
> Should will file an upstream bug for tls not having a context?

I think we should (as long as there isn’t an existing open issue).

**Comment by miekg** [comment]
closing here (it is documented in the source)

**Comment by buffrr** [comment]
Go 1.15 now has a dialer in the tls package with context support https://golang.org/pkg/crypto/tls/#Dialer.DialContext

Any chance of bumping the min go version? I know it has been recently set to Go 1.14 so not sure if its too soon for this but Go 1.16 is out now

**Comment by miekg** [comment]
We support the last 2 go versions, so 1.14 is the new minimum.

**Comment by tmthrgd** [comment]
Go1.17 should be out quite soon, feel free to send a PR once it’s been released.
